[project]
name = "ml-zoomcamp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "v1ct0r3x", email = "victorvickuat@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
]

[project.scripts]
ml-zoomcamp = "ml_zoomcamp:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
